// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Exec(arg1, arg2, arg3) {
  return window['go']['client']['ClientApp']['Exec'](arg1, arg2, arg3);
}

export function GetShellID() {
  return window['go']['client']['ClientApp']['GetShellID']();
}

export function GetShellList(arg1) {
  return window['go']['client']['ClientApp']['GetShellList'](arg1);
}

export function InitShell(arg1) {
  return window['go']['client']['ClientApp']['InitShell'](arg1);
}

export function TestConnect(arg1) {
  return window['go']['client']['ClientApp']['TestConnect'](arg1);
}
