// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddNewShell(arg1) {
  return window['go']['client']['ClientApp']['AddNewShell'](arg1);
}

export function CloseTerminal(arg1) {
  return window['go']['client']['ClientApp']['CloseTerminal'](arg1);
}

export function CreateTerminal(arg1) {
  return window['go']['client']['ClientApp']['CreateTerminal'](arg1);
}

export function Exec(arg1, arg2, arg3) {
  return window['go']['client']['ClientApp']['Exec'](arg1, arg2, arg3);
}

export function ExecuteCommand(arg1, arg2) {
  return window['go']['client']['ClientApp']['ExecuteCommand'](arg1, arg2);
}

export function GetActiveConnections() {
  return window['go']['client']['ClientApp']['GetActiveConnections']();
}

export function GetListeningPorts() {
  return window['go']['client']['ClientApp']['GetListeningPorts']();
}

export function GetLocalSystemMetrics() {
  return window['go']['client']['ClientApp']['GetLocalSystemMetrics']();
}

export function GetNetworkInterfaces() {
  return window['go']['client']['ClientApp']['GetNetworkInterfaces']();
}

export function GetNextCommand(arg1) {
  return window['go']['client']['ClientApp']['GetNextCommand'](arg1);
}

export function GetPreviousCommand(arg1) {
  return window['go']['client']['ClientApp']['GetPreviousCommand'](arg1);
}

export function GetShellID() {
  return window['go']['client']['ClientApp']['GetShellID']();
}

export function GetShellList(arg1) {
  return window['go']['client']['ClientApp']['GetShellList'](arg1);
}

export function GetTerminalEnvironment(arg1, arg2) {
  return window['go']['client']['ClientApp']['GetTerminalEnvironment'](arg1, arg2);
}

export function GetTerminalInfo(arg1) {
  return window['go']['client']['ClientApp']['GetTerminalInfo'](arg1);
}

export function GetTerminalPrompt(arg1) {
  return window['go']['client']['ClientApp']['GetTerminalPrompt'](arg1);
}

export function GetTerminalWelcomeMessage(arg1) {
  return window['go']['client']['ClientApp']['GetTerminalWelcomeMessage'](arg1);
}

export function InitShell(arg1) {
  return window['go']['client']['ClientApp']['InitShell'](arg1);
}

export function ListTerminals() {
  return window['go']['client']['ClientApp']['ListTerminals']();
}

export function SetTerminalEnvironment(arg1, arg2, arg3) {
  return window['go']['client']['ClientApp']['SetTerminalEnvironment'](arg1, arg2, arg3);
}

export function TestConnect(arg1) {
  return window['go']['client']['ClientApp']['TestConnect'](arg1);
}
