// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EnterWebShell(arg1) {
  return window['go']['client']['ClientApp']['EnterWebShell'](arg1);
}

export function GetShellList(arg1) {
  return window['go']['client']['ClientApp']['GetShellList'](arg1);
}
