// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {client} from '../models';

export function EnterWebShell(arg1:client.WebShellItem):Promise<number>;

export function GetShellList(arg1:number):Promise<Array<client.WebShellItem>>;
