// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {client} from '../models';
import {core} from '../models';

export function Exec(arg1:number,arg2:string,arg3:string):Promise<string>;

export function GetShellID():Promise<number>;

export function GetShellList(arg1:number):Promise<Array<client.WebShellItem>>;

export function InitShell(arg1:number):Promise<core.SystemInfo>;

export function TestConnect(arg1:number):Promise<boolean>;
