// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {webshell} from '../models';

export function Greet():Promise<string>;

export function StartWebShell():Promise<webshell.WebClient>;
